[package]
name = "syq"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
regex = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
tokio = "1"
reqwest = "0.11"
clap = { version = "3.2.17", features = ["derive"] }
